language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
